# server
server:
  port: 9999
# spring
spring:
  application:
    name: epoch-demo-starter-metric

# health check management
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway
