# server
server:
  port: 9999
# spring
spring:
  application:
    name: epoch-scaffold-lock

# epoch lock
epoch:
  lock:
    single-server:
      address: localhost
      port: 6379

# logging
logging:
  level:
    org.epoch: debug

# health check management
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway
